spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hnc_store
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  trial-number: ${TWILIO_TRIAL_NUMBER}